version: '3'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=GovindSingh
      - N8N_BASIC_AUTH_PASSWORD=Singh@9447
